"""Proved, not estimated — measurable conditions compiled to Lean 4 and checked by the Lean kernel.

The theorem states the arithmetic on the EXTRACTED facts (minutes). It proves the arithmetic, not the
extraction nor the law: the UI says so. With a Mistral key and MISTRAL_LEAN_MODEL, Leanstral is asked to
write the proof; whatever it writes, the local Lean kernel is the judge. Without Leanstral, the proof
`by decide` is generated by us and still checked by Lean.
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
import subprocess
from datetime import datetime

from casebreak.config import CACHE, settings
from casebreak.llm import mistral
from casebreak.schemas import Check

log = logging.getLogger(__name__)
LEAN_DIR = CACHE / "lean"
LEAN_DIR.mkdir(parents=True, exist_ok=True)


def _ident(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", s)


def statement(c: Check) -> dict | None:
    """Build the Lean theorem for a check that carries proof facts."""
    f = c.details.get("proof_facts")
    if not f:
        return None
    kind = f["kind"]
    header = (f"/-! CASEBREAK · {c.nullity_id} · {c.node_id}\n"
              f"    {c.statement_fr}\n"
              "    Proves the arithmetic on the extracted facts — not the extraction, not the law. -/\n")
    if kind.startswith("duration"):
        a, b = datetime.fromisoformat(f["start"]), datetime.fromisoformat(f["end"])
        day0 = a.replace(hour=0, minute=0)
        ma = int((a - day0).total_seconds() // 60)
        mb = int((b - day0).total_seconds() // 60)
        lim = int(f["limit_minutes"])
        rel = {"duration_gt": ">", "duration_le": "≤", "duration_lt": "<"}[kind]
        name = {"duration_gt": "gap_exceeds_bound", "duration_le": "gap_within_bound",
                "duration_lt": "wait_below_bound"}[kind]
        srcs = "\n".join(f"-- p. {s.page} \"{s.quote[:90]}\"" for s in c.sources[:3])
        code = (header + f"-- Minutes elapsed since {day0:%d/%m/%Y} 00:00\n{srcs}\n"
                f"def start : Nat := {ma}   -- {a:%d/%m %H:%M}\n"
                f"def finish : Nat := {mb}   -- {b:%d/%m %H:%M}\n"
                f"def bound : Nat := {lim}   -- {lim // 60}h{lim % 60:02d}\n\n"
                f"theorem {name} : finish - start {rel} bound := by\n  PROOF\n\n"
                f"#eval finish - start  -- {mb - ma} minutes\n")
        human = f"end − start = {mb - ma} min {rel} {lim} min"
    elif kind.startswith("clock"):
        h, m = map(int, f["start_clock"].split(":"))
        bh, bm = map(int, f["bound"].split(":"))
        rel = "≥" if kind == "clock_ge" else "<"
        code = (header + f"def start_clock : Nat := {h * 60 + m}   -- {h:02d}:{m:02d}\n"
                f"def bound : Nat := {bh * 60 + bm}   -- {bh:02d}:{bm:02d}\n\n"
                f"theorem outside_legal_hours : start_clock {rel} bound := by\n  PROOF\n")
        human = f"{h * 60 + m} min {rel} {bh * 60 + bm} min (since midnight)"
    else:
        return None
    return {"template": code, "human": human}


def _leanstral(code: str) -> str | None:
    if not (settings.mistral and settings.lean_model):
        return None
    try:
        out = mistral.chat([{"role": "system", "content": "You are a Lean 4 prover. Return only the tactic proof that "
                             "replaces PROOF, no prose, no code fences."},
                            {"role": "user", "content": code}], model=settings.lean_model)
        return out.strip().strip("`").replace("lean\n", "")
    except mistral.MistralUnavailable:
        return None


def prove(c: Check) -> dict:
    st = statement(c)
    if st is None:
        return {"status": "not_applicable", "reason": "Not a measurable condition (grey zone or absence): nothing to prove."}
    key = hashlib.sha256(st["template"].encode()).hexdigest()[:16]
    cache = LEAN_DIR / f"{key}.json"
    if cache.exists():
        return json.loads(cache.read_text())
    prover, tactic = "casebreak", "decide"
    ls = _leanstral(st["template"])
    if ls:
        prover, tactic = "leanstral", ls
    code = st["template"].replace("PROOF", tactic)
    res = {"code": code, "human": st["human"], "prover": prover, "lean": None, "status": "unchecked",
           "scope": "Proves the arithmetic on the extracted facts, not the extraction nor the law."}
    lean = settings.lean
    if lean is None:
        res["reason"] = "Lean 4 not installed: proof generated, not checked."
    else:
        res.update(_check(lean, code, key))
        if res["status"] != "proved" and prover == "leanstral":  # fall back to our own tactic, still kernel-checked
            code = st["template"].replace("PROOF", "decide")
            res.update({"code": code, "prover": "casebreak (fallback)"}, **_check(lean, code, key))
    cache.write_text(json.dumps(res, ensure_ascii=False))
    return res


def _check(lean: str, code: str, key: str) -> dict:
    f = LEAN_DIR / f"P{key}.lean"
    f.write_text(code)
    try:
        v = subprocess.run([lean, "--version"], capture_output=True, text=True, timeout=30).stdout.strip()
        p = subprocess.run([lean, str(f)], capture_output=True, text=True, timeout=120)
    except (subprocess.TimeoutExpired, OSError) as e:
        return {"status": "error", "lean": None, "output": str(e)}
    ok = p.returncode == 0 and "error" not in p.stdout.lower()
    return {"status": "proved" if ok else "failed", "lean": v, "output": (p.stdout + p.stderr).strip()[-1200:]}
