"""Report — "grounds of nullity to examine", each with pages and acts to name. Markdown and PDF."""

from __future__ import annotations

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import HRFlowable, KeepTogether, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

ORANGE = colors.HexColor("#FA500F")
INK = colors.HexColor("#151524")
GREY = colors.HexColor("#6B6B78")

DISCLAIMER = ("Working document generated by CASEBREAK from a synthetic case file. It lists grounds to "
              "examine: it concludes neither on nullity nor on prejudice (art. 171 and 802 CPP). Every finding points to a "
              "page of the file; the legal content has not been validated by a lawyer.")


DISCLAIMER_UK = ("Working document generated by CASEBREAK from a synthetic reconstruction. It lists points to examine: it "
                 "concludes neither on the statutory time limit nor on the outcome of the case. Every finding points to a "
                 "page of the file; the legal content has not been validated by a lawyer.")


def _disclaimer(cards: list[dict]) -> str:
    return DISCLAIMER_UK if cards and all(c.get("jurisdiction", "FR") != "FR" for c in cards) else DISCLAIMER


def _order(cards: list[dict]) -> list[dict]:
    keep = [c for c in cards if c["review"].get("decision") != "rejected"]
    return sorted(keep, key=lambda c: (c["review"].get("decision") != "accepted", -c["rank"]))


def markdown(title: str, cards: list[dict], deadline: dict, mode: str = "defense") -> str:
    parquet = mode == "prosecution"
    head = "Regularity audit — issues to fix" if parquet else "Grounds of nullity to examine"
    lines = [f"# {head}", "", f"**Case file:** {title}  ", f"**Generated:** {datetime.now():%d/%m/%Y %H:%M}  ",
             f"**Mode:** {'prosecution (regularity audit)' if parquet else 'defence'}", "", f"> {_disclaimer(cards)}", ""]
    if deadline.get("anchors"):
        lines += ["## Deadline (to verify)", ""]
        for a in deadline["anchors"]:
            lines.append(f"- **{a['person']}** — formally charged on {a['anchor']}:")
            for r in a["regimes"]:
                lines.append(f"  - {r['months']} months ({r['label']}) → **{r['deadline']}** ({r['days_left']} days)")
        lines += ["", f"_{deadline['note']}_", ""]
    rejected = 0
    lines += [f"## {'Issues' if parquet else 'Grounds'} ({len(_order(cards))})", ""]
    for i, c in enumerate(_order(cards), 1):
        st = {"accepted": "accepted by the lawyer", "pending": "to examine"}.get(c["review"].get("decision"), "")
        lines += [f"### {i}. {c['title']} — {c['nullity_id']}",
                  f"*{c['headline']}* · certainty: **{c['certainty_label']}** · {st}", "",
                  f"**Finding.** {c['what']}", "",
                  f"**Rule.** {c['why']['article']} — {c['why']['law_version']}", ""]
        lines.append("**Sources.**")
        for s in c["where"]:
            num = f"report no. {s['piece']['number']}, " if s.get("piece") and s["piece"].get("number") else ""
            lines.append(f"- {num}doc {s['doc_id']}, p. {s['page']}: \"{s['quote']}\"")
        if c["why"]["affected"]:
            lines += ["", f"**Potentially affected acts to name ({len(c['why']['affected'])}).**"]
            for a in c["why"]["affected"]:
                pcs = ", ".join(f"doc {p['cote']}" + (f" (report no. {p['number']})" if p["number"] else "") for p in a["pieces"])
                dashed = " — link inferred by the model" if a["origin"] == "llm_inferred" else ""
                lines.append(f"- {a['label']} — {pcs}{dashed}")
        if c.get("tribunal"):
            t = c["tribunal"]
            lines += ["", f"**Simulated cross-examination.** {t['presiding']['label']} — {t['presiding']['text']}"]
            for o in t["prosecution"]["objections"]:
                src = f" (p. {o['source']['page']})" if o.get("source") else ""
                lines.append(f"- Prosecution: {o['text']} [{o['strength'].replace('_', ' ')}]{src}")
        if c.get("precedents", {}).get("results"):
            lines += ["", "**Precedents retrieved (Judilibre).**"]
            for p in c["precedents"]["results"]:
                lines.append(f"- Crim., {p['date']}, no. {p['number']} — {p.get('solution') or ''} — {p['url']}")
        lines += ["", "**Next steps.**"] + [f"- {s}" for s in c["next"]]
        if c["why"]["legal_todo"]:
            lines += [f"- TODO(legal): {t}" for t in c["why"]["legal_todo"]]
        lines += ["", "---", ""]
    rejected = sum(1 for c in cards if c["review"].get("decision") == "rejected")
    if rejected:
        lines.append(f"_{rejected} alert(s) dismissed by the lawyer, not included._")
    return "\n".join(lines)


def pdf(title: str, cards: list[dict], deadline: dict, mode: str = "defense") -> bytes:
    parquet = mode == "prosecution"
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm,
                            bottomMargin=16 * mm, title=title, author="CASEBREAK")
    ss = getSampleStyleSheet()
    H1 = ParagraphStyle("h1", parent=ss["Title"], fontName="Helvetica-Bold", fontSize=22, textColor=INK, alignment=TA_LEFT,
                        spaceAfter=4)
    H2 = ParagraphStyle("h2", parent=ss["Heading2"], fontName="Helvetica-Bold", fontSize=13, textColor=INK, spaceBefore=10)
    H3 = ParagraphStyle("h3", parent=ss["Heading3"], fontName="Helvetica-Bold", fontSize=11.5, textColor=INK, spaceBefore=6)
    B = ParagraphStyle("b", parent=ss["BodyText"], fontName="Helvetica", fontSize=9.4, leading=13, textColor=INK)
    S = ParagraphStyle("s", parent=B, fontSize=8.2, leading=11, textColor=GREY)
    Q = ParagraphStyle("q", parent=B, fontName="Times-Italic", fontSize=9.6, leftIndent=8, borderPadding=4,
                       textColor=colors.HexColor("#2B2B3A"))
    TAG = ParagraphStyle("tag", parent=S, textColor=ORANGE, fontName="Helvetica-Bold")

    def esc(s: str) -> str:
        return (s or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    story = [Paragraph("CASEBREAK", TAG),
             Paragraph("Regularity audit — issues to fix" if parquet else "Grounds of nullity to examine", H1),
             Paragraph(f"{esc(title)} · generated {datetime.now():%d/%m/%Y %H:%M}", S), Spacer(1, 4),
             HRFlowable(width="100%", thickness=2, color=ORANGE), Spacer(1, 6), Paragraph(esc(_disclaimer(cards)), S)]
    if deadline.get("anchors"):
        story.append(Paragraph("Deadline — to verify", H2))
        rows = [["Person", "Formal charge", "Regime", "Deadline", "Days"]]
        for a in deadline["anchors"]:
            for r in a["regimes"]:
                rows.append([a["person"], a["anchor"], f"{r['months']} months — {r['label']}", r["deadline"], str(r["days_left"])])
        t = Table(rows, colWidths=[38 * mm, 26 * mm, 62 * mm, 24 * mm, 14 * mm])
        t.setStyle(TableStyle([("FONT", (0, 0), (-1, -1), "Helvetica", 8), ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 8),
                               ("LINEBELOW", (0, 0), (-1, 0), 1, INK), ("ROWBACKGROUNDS", (0, 1), (-1, -1),
                                                                         [colors.white, colors.HexColor("#FFF4EC")])]))
        story += [t, Paragraph(esc(deadline["note"]), S)]
    ordered = _order(cards)
    story.append(Paragraph(f"{'Issues' if parquet else 'Grounds'} ({len(ordered)})", H2))
    for i, c in enumerate(ordered, 1):
        block = [Paragraph(f"{i}. {esc(c['title'])} <font color='#FA500F'>· {c['nullity_id']}</font>", H3),
                 Paragraph(f"{esc(c['headline'])} · certainty: <b>{c['certainty_label']}</b>", S),
                 Paragraph(f"<b>Finding.</b> {esc(c['what'])}", B),
                 Paragraph(f"<b>Rule.</b> {esc(c['why']['article'])} — {esc(c['why']['law_version'])}", B)]
        for s in c["where"]:
            num = f"report no. {s['piece']['number']}, " if s.get("piece") and s["piece"].get("number") else ""
            block.append(Paragraph(f"\"{esc(s['quote'])}\" <font size=7 color='#6B6B78'>— {num}doc {s['doc_id']}, p. {s['page']}</font>", Q))
        if c["why"]["affected"]:
            items = "; ".join(f"{esc(a['label'])} ({', '.join(p['cote'] for p in a['pieces'])})" for a in c["why"]["affected"])
            block.append(Paragraph(f"<b>Potentially affected acts ({len(c['why']['affected'])}).</b> {items}", B))
        if c.get("tribunal"):
            block.append(Paragraph(f"<b>Simulated cross-examination.</b> {esc(c['tribunal']['presiding']['label'])}.", B))
        block.append(Paragraph("<b>Next steps.</b> " + esc(" ".join(c["next"])), B))
        block += [Spacer(1, 3), HRFlowable(width="100%", thickness=0.4, color=colors.HexColor("#E7E2DC"))]
        story.append(KeepTogether(block))
    doc.build(story)
    return buf.getvalue()
